### PR TITLE
Feature/https gradle

### PR DESCRIPTION
**Pull request by keiranmraine**
Makes it possible to install since maven repositories only allow https now.

Must be compiled with java 1.8/8.  I used openjdk due to site preference which required an update to gradle.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
My only query:

Will using `-XX:CICompilerCount=2` require more CPUs when we run a bpipe farm job?

**Comment by keiranmraine** [comment]
It's not possible to run it with 1 anymore JAVA says no.  I'm pretty sure it's not even relevant as it's using code that's already compiled.  It being hotspot there's a small possibility of a some JIT re-compilation however I think it's probably trumped by a different variable:

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8029436

**Comment by ghost** [comment]
I hadn't seen that it was overridden by that other variable. I'd seen the fact it had to be >1. 
That ticket isn't clear, do we need to set `-XX:+CICompilerCountPerCPU` ourselves then?

**Comment by keiranmraine** [comment]
I don't think we should change anything that we don't physically have to to make it run, the process spends 99.999% of time sleeping in our implementation.  If there are issues when actually running it on the new platform I may tune it further but I really don't want to change anything that isn't absolutely necessary.

**Review by ghost — APPROVED** [review]

**Pull request merged**
